# Generated by Django 4.0.4 on 2022-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('temp', models.DecimalField(decimal_places=2, max_digits=3)),
                ('hum', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
