# Generated by Django 4.0.4 on 2022-04-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
