# Generated by Django 4.0.4 on 2022-04-18 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
