# Generated by Django 4.0.4 on 2022-04-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='datetime',
        ),
    ]
