# Generated by Django 4.0.4 on 2022-04-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_remove_sensordata_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default='2021-06-25'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='hum',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
