# Generated by Django 4.0.6 on 2022-08-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_sensordata_datetime_alter_sensordata_hum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
