# Generated by Django 4.0.4 on 2022-08-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_lightdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightdata',
            name='brightness',
            field=models.IntegerField(default=-999),
        ),
    ]
